<h1> Plug.ErrorHandler   </h1> <section id="moduledoc"> <p>A module to be used in your existing plugs in order to provide error handling.</p>
<pre data-language="elixir">defmodule AppRouter do
  use Plug.Router
  use Plug.ErrorHandler

  plug :match
  plug :dispatch

  get "/hello" do
    send_resp(conn, 200, "world")
  end

  def handle_errors(conn, %{kind: _kind, reason: _reason, stack: _stack}) do
    send_resp(conn, conn.status, "Something went wrong")
  end
end</pre>
<p>Once this module is used, a callback named <code class="inline">handle_errors/2</code> should be defined in your plug. This callback will receive the connection already updated with a proper status code for the given exception. The second argument is a map containing:</p>
<ul>
<li>the exception kind (<code class="inline">:throw</code>, <code class="inline">:error</code> or <code class="inline">:exit</code>),</li>
<li>the reason (an exception for errors or a term for others)</li>
<li>the stacktrace</li>
</ul>
<p>After the callback is invoked, the error is re-raised.</p>
<p>It is advised to do as little work as possible when handling errors and avoid accessing data like parameters and session, as the parsing of those is what could have led the error to trigger in the first place.</p>
<p>Also notice that these pages are going to be shown in production. If you are looking for error handling to help during development, consider using <a href="../plug.debugger"><code class="inline">Plug.Debugger</code></a>.</p>
<p><strong>Note:</strong> If this module is used with <a href="../plug.debugger"><code class="inline">Plug.Debugger</code></a>, it must be used after <a href="../plug.debugger"><code class="inline">Plug.Debugger</code></a>.</p> </section><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://hexdocs.pm/plug/1.11.0/Plug.ErrorHandler.html" class="_attribution-link" target="_blank">https://hexdocs.pm/plug/1.11.0/Plug.ErrorHandler.html</a>
  </p>
</div>
