<h1 id="troubleshooting-koa">Troubleshooting Koa</h1> <ul> <li><a href="#whenever-i-try-to-access-my-route-it-sends-back-a-404">Whenever I try to access my route, it sends back a 404</a></li> <li><a href="#my-response-or-context-changes-have-no-effect">My response or context changes have no effect</a></li> <li><a href="#my-middleware-is-not-called">My middleware is not called</a></li> </ul> <p>See also <a href="guide.md#debugging-koa">debugging Koa</a>.</p> <p>If you encounter a problem and later learn how to fix it, and think others might also encounter that problem, please consider contributing to this documentation.</p> <h2 id="whenever-i-try-to-access-my-route-it-sends-back-a-404">Whenever I try to access my route, it sends back a 404</h2> <p>This is a common but troublesome problem when working with Koa middleware. First, it is critical to understand when Koa generates a 404. Koa does not care which or how much middleware was run, in many cases a 200 and 404 trigger the same number of middleware. Instead, the default status for any response is 404. The most obvious way this is changed is through <code>ctx.status</code>. However, if <code>ctx.body</code> is set when the status has not been explicitly defined (through <code>ctx.status</code>), the status is set to 200. This explains why simply setting the body results in a 200. Once the middleware is done (when the middleware and any returned promises are complete), Koa sends out the response. After that, nothing can alter the response. If it was a 404 at the time, it will be a 404 at the end, even if <code>ctx.status</code> or <code>ctx.body</code> are set afterwords.</p> <p>Even though we now understand the basis of a 404, it might not be as clear why a 404 is generated in a specific case. This can be especially troublesome when it seems that <code>ctx.status</code> or <code>ctx.body</code> are set.</p> <p>The unexpected 404 is a specific symptom of one of these more general problems:</p> <ul> <li><a href="#my-response-or-context-changes-have-no-effect">My response or context changes have no effect</a></li> <li><a href="#my-middleware-is-not-called">My middleware is not called</a></li> </ul> <h2 id="my-response-or-context-changes-have-no-effect">My response or context changes have no effect</h2> <p>This can be caused when the response is sent before the code making the change is executed. If the change is to the <code>ctx.body</code> or <code>ctx.status</code> setter, this can cause a 404 and is by far the most common cause of these problems.</p> <h3 id="problematic-code">Problematic code</h3> <pre data-language="js">router.get('/fetch', function (ctx, next) {
  models.Book.findById(parseInt(ctx.query.id)).then(function (book) {
    ctx.body = book;
  });
});</pre> <p>When used, this route will always send back a 404, even though <code>ctx.body</code> is set.</p> <p>The same behavior would occur in this <code>async</code> version:</p> <pre data-language="js">router.get('/fetch', async (ctx, next) =&gt; {
  models.Book.findById(parseInt(ctx.query.id)).then(function (book) {
    ctx.body = book;
  });
});</pre> <h3 id="cause">Cause</h3> <p><code>ctx.body</code> is not set until <em>after</em> the response has been sent. The code doesn't tell Koa to wait for the database to return the record. Koa sends the response after the middleware has been run, but not after the callback inside the middleware has been run. In the gap there, <code>ctx.body</code> has not yet been set, so Koa responds with a 404.</p> <h3 id="identifying-this-as-the-issue">Identifying this as the issue</h3> <p>Adding another piece of middleware and some logging can be extremely helpful in identifying this issue.</p> <pre data-language="js">router.use('/fetch', function (ctx, next) {
  return next().then(function () {
    console.log('Middleware done'); 
  }); 
});

router.get('/fetch', function (ctx, next) {
  models.Book.findById(parseInt(ctx.query.id)).then(function (book) {
    ctx.body = book;
    console.log('Body set');
  });
});</pre> <p>If you see this in the logs:</p> <div class="snippet-clipboard-content position-relative" data-snippet-clipboard-copy-content="Middleware done 
Body set
"><pre>Middleware done 
Body set
</pre></div> <p>It means that the body is being set after the middleware is done, and after the response has been sent. If you see only one or none of these logs, proceed to <a href="#my-middleware-is-not-called">My middleware is not called</a>. If they are in the right order, make sure you haven't explicitly set the status to 404, make sure that it actually is a 404, and if that fails feel free to ask for help.</p> <h3 id="solution">Solution</h3> <pre data-language="js">router.get('/fetch', function (ctx, next) {
  return models.Book.findById(parseInt(ctx.query.id)).then(function (book) {
    ctx.body = book;
  });
});</pre> <p>Returning the promise given by the database interface tells Koa to wait for the promise to finish before responding. At that time, the body will have been set. This results in Koa sending back a 200 with a proper response.</p> <p>The fix in the <code>async</code> version is to add an <code>await</code> statement:</p> <pre data-language="js">router.get('/fetch', async (ctx, next) =&gt; {
  await models.Book.findById(parseInt(ctx.query.id)).then(function (book) {
    ctx.body = book;
  });
});</pre> <h2 id="my-middleware-is-not-called">My middleware is not called</h2> <p>This can be due to an interrupted chain of middleware calls. This can cause a 404 if the middleware that is skipped is responsible for the <code>ctx.body</code> or <code>ctx.status</code> setter. This is less common than <a href="#my-response-or-context-changes-have-no-effect">My response or context changes have no effect</a>, but it can be a much bigger pain to troubleshoot.</p> <h3 id="problematic-code-1">Problematic code</h3> <pre data-language="js">router.use(function (ctx, next) {
  // Don't Repeat Yourself! Let's parse the ID here for all our middleware
  if (ctx.query.id) {
    ctx.state.id = parseInt(ctx.query.id);
  }
});

router.get('/fetch', function (ctx, next) {
  return models.Book.findById(ctx.state.id).then(function (book) {
    ctx.body = book;
  });
});</pre> <h3 id="cause-1">Cause</h3> <p>In the code above, the book is never fetched from the database, and in fact our route was never called. Look closely at our helper middleware. We forgot to <code>return next()</code>! This causes the middleware flow to never reach our route, ending our "helper" middleware.</p> <h3 id="identifying-this-as-the-issue-1">Identifying this as the issue</h3> <p>Identifying this problem is easier than most, add a log at the beginning of the route. If it doesn't trigger, your route was never reached in the middleware chain.</p> <pre data-language="js">router.use(function (ctx, next) {
  // Don't Repeat Yourself! Let's parse the ID here for all our middleware
  if (ctx.query.id) {
    ctx.state.id = parseInt(ctx.query.id);
  }
});

router.get('/fetch', function (ctx, next) {
  console.log('Route called'); // Never happens
  return models.Book.findById(ctx.state.id).then(function (book) {
    ctx.body = book;
  });
});</pre> <p>To find the middleware causing the problem, try adding logging at various points in the middleware chain.</p> <h3 id="solution-1">Solution</h3> <p>The solution for this is rather easy, simply add <code>return next()</code> to the end of your helper middleware.</p> <pre data-language="js">router.use(function (ctx, next) {
  if (ctx.query.id) {
    ctx.state.id = parseInt(ctx.query.id);
  }
  return next();
});

router.get('/fetch', function (ctx, next) {
  return models.Book.findById(ctx.state.id).then(function (book) {
    ctx.body = book;
  });
});</pre><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://github.com/koajs/koa/blob/master/docs/troubleshooting.md" class="_attribution-link" target="_blank">https://github.com/koajs/koa/blob/master/docs/troubleshooting.md</a>
  </p>
</div>
