
<h1 id="disallow-async-functions-which-have-no-await-expression-require-await">Disallow async functions which have no <code>await</code> expression (require-await)</h1>
<p>Asynchronous functions in JavaScript behave differently than other functions in two important ways:</p>
<ol>
<li>The return value is always a <code>Promise</code>.</li>
<li>You can use the <code>await</code> operator inside of them.</li>
</ol>
<p>The primary reason to use asynchronous functions is typically to use the <code>await</code> operator, such as this:</p>
<pre data-language="js">async function fetchData(processDataItem) {
    const response = await fetch(DATA_URL);
    const data = await response.json();

    return data.map(processDataItem);
}</pre>
<p>Asynchronous functions that don't use <code>await</code> might not need to be asynchronous functions and could be the unintentional result of refactoring.</p>
<p>Note: this rule ignores async generator functions. This is because generators yield rather than return a value and async generators might yield all the values of another async generator without ever actually needing to use await.</p>
<h2 id="rule-details">Rule Details</h2>
<p>This rule warns async functions which have no <code>await</code> expression.</p>
<p>Examples of <strong>incorrect</strong> code for this rule:</p>
<pre data-language="js">/*eslint require-await: "error"*/

async function foo() {
    doSomething();
}

bar(async () =&gt; {
    doSomething();
});</pre>
<p>Examples of <strong>correct</strong> code for this rule:</p>
<pre data-language="js">/*eslint require-await: "error"*/

async function foo() {
    await doSomething();
}

bar(async () =&gt; {
    await doSomething();
});

function foo() {
    doSomething();
}

bar(() =&gt; {
    doSomething();
});

// Allow empty functions.
async function noop() {}</pre>
<h2 id="when-not-to-use-it">When Not To Use It</h2>
<p>Asynchronous functions are designed to work with promises such that throwing an error will cause a promise's rejection handler (such as <code>catch()</code>) to be called. For example:</p>
<pre data-language="js">async function fail() {
    throw new Error("Failure!");
}

fail().catch(error =&gt; {
    console.log(error.message);
});</pre>
<p>In this case, the <code>fail()</code> function throws an error that is intended to be caught by the <code>catch()</code> handler assigned later. Converting the <code>fail()</code> function into a synchronous function would require the call to <code>fail()</code> to be refactored to use a <code>try-catch</code> statement instead of a promise.</p>
<p>If you are throwing an error inside of an asynchronous function for this purpose, then you may want to disable this rule.</p>
<h2 id="related-rules">Related Rules</h2>
<ul><li><a href="require-yield">require-yield</a></li></ul>
<h2 id="version">Version</h2>
<p>This rule was introduced in ESLint 3.11.0.</p>
<h2 id="resources">Resources</h2>
<ul>
<li><a href="https://github.com/eslint/eslint/tree/master/lib/rules/require-await.js">Rule source</a></li>
<li><a href="https://github.com/eslint/eslint/tree/master/docs/rules/require-await.md">Documentation source</a></li>
</ul><div class="_attribution">
  <p class="_attribution-p">
    <a href="https://eslint.org/docs/rules/require-await" class="_attribution-link" target="_blank">https://eslint.org/docs/rules/require-await</a>
  </p>
</div>
