<h1>Class JMXServerErrorException</h1>   <ul class="inheritance"> <li><a href="../../../java/lang/object">java.lang.Object</a></li> <li> <ul class="inheritance"> <li><a href="../../../java/lang/throwable">java.lang.Throwable</a></li> <li> <ul class="inheritance"> <li><a href="../../../java/lang/exception">java.lang.Exception</a></li> <li> <ul class="inheritance"> <li><a href="../../../java/io/ioexception">java.io.IOException</a></li> <li> <ul class="inheritance"> <li>javax.management.remote.JMXServerErrorException</li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul>   <dl> <dt>All Implemented Interfaces:</dt> <dd><a href="../../../java/io/serializable">Serializable</a></dd> </dl>   <pre data-language="java">public class JMXServerErrorException
extends IOException</pre> <p>Exception thrown as the result of a remote <a href="../mbeanserver"><code>MBeanServer</code></a> method invocation when an <code>Error</code> is thrown while processing the invocation in the remote MBean server. A <code>JMXServerErrorException</code> instance contains the original <code>Error</code> that occurred as its cause.</p> <dl> <dt>Since:</dt> <dd>1.5</dd> <dt>See Also:</dt> <dd>
<a href="/openjdk~8_web/java/rmi/servererror"><code>ServerError</code></a>, Serialized Form</dd> </dl>       <h2 id="constructor.detail">Constructors</h2>   <h3 id="JMXServerErrorException-java.lang.String-java.lang.Error-">JMXServerErrorException</h3> <pre data-language="java">public JMXServerErrorException(String s,
                               Error err)</pre> <p>Constructs a <code>JMXServerErrorException</code> with the specified detail message and nested error.</p> <dl> <dt>Parameters:</dt> <dd>
<code>s</code> - the detail message.</dd> <dd>
<code>err</code> - the nested error. An instance of this class can be constructed where this parameter is null, but the standard connectors will never do so.</dd> </dl>     <h2 id="method.detail">Methods</h2>   <h3 id="getCause--">getCause</h3> <pre data-language="java">public Throwable getCause()</pre> <p>Description copied from class: <code><a href="../../../java/lang/throwable#getCause--">Throwable</a></code></p> <div>
<p>Returns the cause of this throwable or <code>null</code> if the cause is nonexistent or unknown. (The cause is the throwable that caused this throwable to get thrown.) </p>
<p>This implementation returns the cause that was supplied via one of the constructors requiring a <code>Throwable</code>, or that was set after creation with the <a href="../../../java/lang/throwable#initCause-java.lang.Throwable-"><code>Throwable.initCause(Throwable)</code></a> method. While it is typically unnecessary to override this method, a subclass can override it to return a cause set by some other means. This is appropriate for a "legacy chained throwable" that predates the addition of chained exceptions to <code>Throwable</code>. Note that it is <i>not</i> necessary to override any of the <code>PrintStackTrace</code> methods, all of which invoke the <code>getCause</code> method to determine the cause of a throwable.</p>
</div> <dl> <dt>Overrides:</dt> <dd>
<code><a href="../../../java/lang/throwable#getCause--">getCause</a></code> in class <code><a href="../../../java/lang/throwable">Throwable</a></code>
</dd> <dt>Returns:</dt> <dd>the cause of this throwable or <code>null</code> if the cause is nonexistent or unknown.</dd> </dl>     <div class="_attribution">
  <p class="_attribution-p">
    &copy; 1993&ndash;2017, Oracle and/or its affiliates. All rights reserved.<br>Documentation extracted from Debian's OpenJDK Development Kit package.<br>Licensed under the GNU General Public License, version 2, with the Classpath Exception.<br>Various third party code in OpenJDK is licensed under different licenses (see Debian package).<br>Java and OpenJDK are trademarks or registered trademarks of Oracle and/or its affiliates.<br>
    
  </p>
</div>
