   <h1 id="firstHeading" class="firstHeading">Exceptions</h1>            <p>Exception handling provides a way of transferring control and information from some point in the execution of a program to a handler associated with a point previously passed by the execution (in other words, exception handling transfers control up the call stack).</p>
<p>An exception can be thrown by a <a href="throw" title="cpp/language/throw">throw-expression</a>, <a href="dynamic_cast" title="cpp/language/dynamic cast">dynamic_cast</a>, <a href="typeid" title="cpp/language/typeid">typeid</a>, <a href="new" title="cpp/language/new">new-expression</a>, <a href="../memory/new/operator_new" title="cpp/memory/new/operator new">allocation function</a>, and any of the standard library functions that are specified to throw exceptions to signal certain error conditions (e.g. <code><a href="../container/vector/at" title="cpp/container/vector/at">std::vector::at</a></code>, <code><a href="../string/basic_string/substr" title="cpp/string/basic string/substr">std::string::substr</a></code>, etc).</p>
<p>In order for an exception to be caught, the throw-expression has to be inside a <a href="try_catch" title="cpp/language/try catch">try-block</a> or inside a function called from a try-block, and there has to be a <a href="try_catch" title="cpp/language/try catch">catch clause</a> that matches the type of the exception object.</p>
<p>When declaring a function, <a href="except_spec" title="cpp/language/except spec"> exception specifications</a> and <a href="noexcept_spec" title="cpp/language/noexcept spec"> noexcept specifiers</a> may be provided to limit the types of the exceptions a function may throw.</p>
<p>Errors that arise during exception handling are handled by <code><a href="../error/terminate" title="cpp/error/terminate">std::terminate</a></code><span class="t-rev-inl t-until-cxx17"><span> and <code><a href="../error/exception/unexpected" title="cpp/error/unexpected">std::unexpected</a></code></span> <span><span class="t-mark-rev t-until-cxx17">(until C++17)</span></span></span>.</p>
<h3 id="Usage">Usage</h3> <p>While throw-expression can be used to transfer control to an arbitrary block of code up the execution stack, for arbitrary reasons (similar to <code><a href="../utility/program/longjmp" title="cpp/utility/program/longjmp">std::longjmp</a></code>), its intended usage is error handling.</p>
<h4 id="Error_handling">Error handling</h4> <p>Throwing an exception is used to signal errors from functions, where "errors" are typically limited to only the following<sup id="cite_ref-1" class="reference"><a href="exceptions#cite_note-1">[1]</a></sup><sup id="cite_ref-2" class="reference"><a href="exceptions#cite_note-2">[2]</a></sup><sup id="cite_ref-3" class="reference"><a href="exceptions#cite_note-3">[3]</a></sup>:</p>
<ol>
<li> Failures to meet the postconditions, such as failing to produce a valid return value object </li>
<li> Failures to meet the preconditions of another function that must be called </li>
<li> (for non-private member functions) Failures to (re)establish a class invariant </li>
</ol> <p>In particular, this implies that the failures of constructors (see also <a href="raii" title="cpp/language/raii">RAII</a>) and most operators should be reported by throwing exceptions.</p>
<p>In addition, so-called <i>wide contract</i> functions use exceptions to indicate unacceptable inputs, for example, <code><a href="../string/basic_string/at" title="cpp/string/basic string/at">std::string::at</a></code> has no preconditions, but throws an exception to indicate index out of range.</p>
<h4 id="Exception_safety">Exception safety</h4> <p>After the error condition is reported by a function, additional guarantees may be provided with regards to the state of the program. The following four levels of exception guarantee are generally recognized<sup id="cite_ref-4" class="reference"><a href="exceptions#cite_note-4">[4]</a></sup><sup id="cite_ref-5" class="reference"><a href="exceptions#cite_note-5">[5]</a></sup><sup id="cite_ref-6" class="reference"><a href="exceptions#cite_note-6">[6]</a></sup>, which are strict supersets of each other:</p>
<ol>
<li> <i>Nothrow (or nofail) exception guarantee</i> -- the function never throws exceptions. Nothrow (errors are reported by other means or concealed) is expected of <a href="destructor" title="cpp/language/destructor">destructors</a> and other functions that may be called during stack unwinding. <span class="t-rev-inl t-since-cxx11"><span>The <a href="destructor" title="cpp/language/destructor">destructors</a> are <a href="noexcept" title="cpp/language/noexcept">noexcept</a> by default.</span> <span><span class="t-mark-rev t-since-cxx11">(since C++11)</span></span></span> Nofail (the function always succeeds) is expected of swaps, <a href="move_constructor" title="cpp/language/move constructor">move constructors</a>, and other functions used by those that provide strong exception guarantee. </li>
<li> <i>Strong exception guarantee</i> -- If the function throws an exception, the state of the program is rolled back to the state just before the function call. (for example, <code><a href="../container/vector/push_back" title="cpp/container/vector/push back">std::vector::push_back</a></code>) </li>
<li> <i>Basic exception guarantee</i> -- If the function throws an exception, the program is in a valid state. It may require cleanup, but all invariants are intact. </li>
<li> <i>No exception guarantee</i> -- If the function throws an exception, the program may not be in a valid state: resource leaks, memory corruption, or other invariant-destroying errors may have occurred. </li>
</ol> <p>Generic components may, in addition, offer <i>exception-neutral guarantee</i>: if an exception is thrown from a template parameter (e.g. from the <code>Compare</code> function object of <code><a href="../algorithm/sort" title="cpp/algorithm/sort">std::sort</a></code> or from the constructor of <code>T</code> in <code><a href="../memory/shared_ptr/make_shared" title="cpp/memory/shared ptr/make shared">std::make_shared</a></code>), it is propagated, unchanged, to the caller.</p>
<h3 id="Exception_objects">Exception objects</h3> <p>While objects of any complete type and cv pointers to void may be thrown as exception objects, all standard library functions throw anonymous temporary objects by value, and the types of those objects are derived (directly or indirectly) from <code><a href="../error/exception" title="cpp/error/exception">std::exception</a></code>. User-defined exceptions usually follow this pattern.<sup id="cite_ref-7" class="reference"><a href="exceptions#cite_note-7">[7]</a></sup><sup id="cite_ref-8" class="reference"><a href="exceptions#cite_note-8">[8]</a></sup><sup id="cite_ref-9" class="reference"><a href="exceptions#cite_note-9">[9]</a></sup></p>
<p>To avoid unnecessary copying of the exception object and object slicing, the best practice for catch clauses is to catch by reference.<sup id="cite_ref-10" class="reference"><a href="exceptions#cite_note-10">[10]</a></sup><sup id="cite_ref-11" class="reference"><a href="exceptions#cite_note-11">[11]</a></sup><sup id="cite_ref-12" class="reference"><a href="exceptions#cite_note-12">[12]</a></sup><sup id="cite_ref-13" class="reference"><a href="exceptions#cite_note-13">[13]</a></sup></p>
<h3 id="References">References</h3> <ol class="references"> <li id="cite_note-1"> <span class="reference-text"> H. Sutter (2004) <a rel="nofollow" class="external text" href="http://www.drdobbs.com/when-and-how-to-use-exceptions/184401836">"When and How to Use Exceptions"</a> in Dr. Dobb's</span> </li> <li id="cite_note-2"> <span class="reference-text">H.Sutter, A. Alexandrescu (2004), "C++ Coding Standards", Item 70</span> </li> <li id="cite_note-3"> <span class="reference-text">C++ Core Guidelines <a rel="nofollow" class="external text" href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#i10-use-exceptions-to-signal-a-failure-to-perform-a-required-task">I.10</a></span> </li> <li id="cite_note-4"> <span class="reference-text">B. Stroustrup (2000), "The C++ Programming Language"<a rel="nofollow" class="external text" href="http://stroustrup.com/3rd_safe.pdf">Appendix E"</a></span> </li> <li id="cite_note-5"> <span class="reference-text">H. Sutter (2000) "Exceptional C++"</span> </li> <li id="cite_note-6"> <span class="reference-text">D. Abrahams (2001) <a rel="nofollow" class="external text" href="http://www.boost.org/community/exception_safety.html">"Exception Safety in Generic Components"</a></span> </li> <li id="cite_note-7"> <span class="reference-text">D. Abrahams (2001) <a rel="nofollow" class="external text" href="http://www.boost.org/community/error_handling.html">"Error and Exception Handling"</a></span> </li> <li id="cite_note-8"> <span class="reference-text">isocpp.org Super-FAQ <a rel="nofollow" class="external text" href="https://isocpp.org/wiki/faq/exceptions#what-to-throw">"What should I throw?"</a></span> </li> <li id="cite_note-9"> <span class="reference-text">C++ Core Guidelines <a rel="nofollow" class="external text" href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#e14-use-purpose-designed-user-defined-types-as-exceptions-not-built-in-types">E.14</a></span> </li> <li id="cite_note-10"> <span class="reference-text">C++ Core Guidelines <a rel="nofollow" class="external text" href="https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#e15-catch-exceptions-from-a-hierarchy-by-reference">E.15</a></span> </li> <li id="cite_note-11"> <span class="reference-text">S. Meyers (1996) "More Effective C++" Item 13</span> </li> <li id="cite_note-12"> <span class="reference-text">isocpp.org Super-FAQ <a rel="nofollow" class="external text" href="https://isocpp.org/wiki/faq/exceptions#what-to-catch">"What should I catch?"</a></span> </li> <li id="cite_note-13"> <span class="reference-text">H.Sutter, A. Alexandrescu (2004) "C++ Coding Standards" Item 73</span> </li> </ol>          <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="http://en.cppreference.com/w/cpp/language/exceptions" class="_attribution-link">http://en.cppreference.com/w/cpp/language/exceptions</a>
  </p>
</div>
