   <h1 id="firstHeading" class="firstHeading">std::bad_exception</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl"> <td class="t-dcl-nopad"> <pre data-language="cpp">class bad_exception;</pre>
</td> <td class="t-dcl-nopad"> </td> <td class="t-dcl-nopad"> </td> </tr>  </table> <p><code>std::bad_exception</code> is the type of the exception thrown by the C++ runtime in the following situations:</p>
<div class="t-li1">
<span class="t-li">1)</span> If <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> stores a copy of the caught exception and if the copy constructor of the exception object caught by <code><a href="current_exception" title="cpp/error/current exception">std::current_exception</a></code> throws an exception, the captured exception is an instance of <code>std::bad_exception</code>.</div> <table class="t-rev-begin"> <tr class="t-rev t-until-cxx17">
<td> <span class="t-li">2)</span> If a <a href="../language/except_spec" title="cpp/language/except spec">dynamic exception specification</a> is violated and <code><a href="exception/unexpected" title="cpp/error/unexpected">std::unexpected</a></code> throws or rethrows an exception that still violates the exception specification, but the exception specification allows <code>std::bad_exception</code>, <code>std::bad_exception</code> is thrown. </td> <td><span class="t-mark-rev t-until-cxx17">(until C++17)</span></td>
</tr> </table> <div class="t-inheritance-diagram"> <div class="center"><div class="noresize" style="height: 40px; width: 243px; ">
<map name="ImageMap_1_114674427"><area href="exception" shape="rect" coords="5,4,107,36" alt="cpp/error/exception" title="cpp/error/exception"></map><img alt="std-bad exception-inheritance.svg" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+CjwhLS0gR2VuZXJhdGVkIGJ5IGdyYXBodml6IHZlcnNpb24gMi4yNi4zICgyMDEwMDEyNi4xNjAwKQogLS0+CjwhLS0gVGl0bGU6IGluaGVyaXRhbmNlIFBhZ2VzOiAxIC0tPgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHdpZHRoPSIyNDNweCIgaGVpZ2h0PSI0MHB4IiB2aWV3Qm94PSIwLjAwIDAuMDAgMjY5LjAwIDQ0LjAwIj4KPGcgaWQ9ImdyYXBoMSIgY2xhc3M9ImdyYXBoIiB0cmFuc2Zvcm09InJvdGF0ZSgwKSB0cmFuc2xhdGUoNCA0MCkiPgo8dGl0bGU+aW5oZXJpdGFuY2U8L3RpdGxlPgo8IS0tIGUxIC0tPgo8ZyBpZD0ibm9kZTEiIGNsYXNzPSJub2RlIj48dGl0bGU+ZTE8L3RpdGxlPgo8YT4KPHBvbHlnb24gZmlsbD0id2hpdGUiIHN0cm9rZT0iYmxhY2siIHBvaW50cz0iMTE1LC0zNiAxLC0zNiAxLC0xLjc3NjM2ZS0xNCAxMTUsLTMuNTUyNzFlLTE1IDExNSwtMzYiLz4KPHRleHQgdGV4dC1hbmNob3I9Im1pZGRsZSIgeD0iNTgiIHk9Ii0xNC40IiBmb250LWZhbWlseT0iRGVqYVZ1IFNhbnMsIHZlcmRhbmEsIHNhbnMtc2VyaWYiIGZvbnQtc2l6ZT0iMTQuMDAiPmV4Y2VwdGlvbjwvdGV4dD4KPC9hPgo8L2c+CjwhLS0gZTIgLS0+CjxnIGlkPSJub2RlMiIgY2xhc3M9Im5vZGUiPjx0aXRsZT5lMjwvdGl0bGU+CjxhPgo8cG9seWdvbiBmaWxsPSJsaWdodGdyZXkiIHN0cm9rZT0iYmxhY2siIHBvaW50cz0iMjYwLC0zNiAxNDYsLTM2IDE0NiwtMS43NzYzNmUtMTQgMjYwLC0zLjU1MjcxZS0xNSAyNjAsLTM2Ii8+Cjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjIwMyIgeT0iLTE0LjQiIGZvbnQtZmFtaWx5PSJEZWphVnUgU2FucywgdmVyZGFuYSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxNC4wMCI+YmFkX2V4Y2VwdGlvbjwvdGV4dD4KPC9hPgo8L2c+CjwhLS0gZTImIzQ1OyZndDtlMSAtLT4KPGcgaWQ9ImVkZ2UyIiBjbGFzcz0iZWRnZSI+PHRpdGxlPmUyLSZndDtlMTwvdGl0bGU+CjxwYXRoIGZpbGw9Im5vbmUiIHN0cm9rZT0iYmxhY2siIGQ9Ik0xNDUuMjc2LC0xOEMxNDAuNTMyLC0xOCAxMzUuNywtMTggMTMwLjg2NywtMTgiLz4KPHBvbHlnb24gZmlsbD0ibm9uZSIgc3Ryb2tlPSJibGFjayIgcG9pbnRzPSIxMzAuNTI2LC0xMi43NTAxIDExNS41MjYsLTE4IDEzMC41MjYsLTIzLjI1MDEgMTMwLjUyNiwtMTIuNzUwMSIvPgo8L2c+CjwvZz4KPC9zdmc+Cg==" width="243" height="40" usemap="#ImageMap_1_114674427">
</div></div> <div style="text-align:center;"> <p>Inheritance diagram.</p>
</div> </div> <h3 id="Member_functions">Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="bad_exception/bad_exception" title="cpp/error/bad exception/bad exception"> <span class="t-lines"><span>(constructor)</span></span></a></div> </td> <td> constructs the <code>bad_exception</code> object <br> <span class="t-mark">(public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="bad_exception/operator=" title="cpp/error/bad exception/operator="> <span class="t-lines"><span>operator=</span></span></a></div> </td> <td> copies the object <br> <span class="t-mark">(public member function)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="bad_exception/what" title="cpp/error/bad exception/what"> <span class="t-lines"><span>what</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> returns the explanatory string <br> <span class="t-mark">(virtual public member function)</span> </td>
</tr> </table> <div class="t-inherited"> <h2 id="Inherited_from_std::exception"> Inherited from <a href="exception" title="cpp/error/exception"> std::exception</a> </h2> <h3 id="Member_functions_2"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception/~exception" title="cpp/error/exception/~exception"> <span class="t-lines"><span>(destructor)</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> destroys the exception object <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span> </td>
</tr> <tr class="t-dsc"> <td> <div><a href="exception/what" title="cpp/error/exception/what"> <span class="t-lines"><span>what</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> returns an explanatory string <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span> </td>
</tr> </table> </div> <h3 id="Example">Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;iostream&gt;
#include &lt;exception&gt;
#include &lt;stdexcept&gt;
 
void my_unexp() { throw; }
 
void test() throw(std::bad_exception)
{
    throw std::runtime_error("test");
}
 
int main()
{
    std::set_unexpected(my_unexp);
    try {
         test();
    } catch(const std::bad_exception&amp; e)
    {
        std::cerr &lt;&lt; "Caught " &lt;&lt; e.what() &lt;&lt; '\n';
    }
}</pre></div> <p>Output:</p>
<div class="text source-text"><pre data-language="c">Caught std::bad_exception</pre></div> </div>          <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="http://en.cppreference.com/w/cpp/error/bad_exception" class="_attribution-link">http://en.cppreference.com/w/cpp/error/bad_exception</a>
  </p>
</div>
