    <h1 id="firstHeading" class="firstHeading">std::system_error</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/system_error" title="cpp/header/system error">&lt;system_error&gt;</a></code> </th> <th> </th> <th> </th> </tr> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">class system_error;</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p><code>std::system_error</code> is the type of the exception thrown by various library functions (typically the functions that interface with the OS facilities, e.g. the constructor of <code><a href="../thread/thread" title="cpp/thread/thread">std::thread</a></code>) when the exception has an associated <code><a href="error_code" title="cpp/error/error code">std::error_code</a></code>, which may be reported.</p>
<div class="t-inheritance-diagram"> <div class="center"><div class="noresize">
<map name="ImageMap_1_2121307341"><area href="/w/cpp/error/exception" shape="rect" coords="5,4,107,36" alt="cpp/error/exception" title="cpp/error/exception">
<area href="/w/cpp/error/runtime_error" shape="rect" coords="135,4,238,36" alt="cpp/error/runtime error" title="cpp/error/runtime error"></map><img alt="std-system error-inheritance.svg" src="" width="374" height="40" usemap="#ImageMap_1_2121307341">
</div></div> <div style="text-align:center;"> <p>Inheritance diagram.</p>
</div> </div>  <h3 id="Member_functions"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="system_error/system_error" title="cpp/error/system error/system error"> <span class="t-lines"><span>(constructor)</span></span></a></div> </td> <td> constructs the <code>system_error</code> object <br> <span class="t-mark">(public member function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="system_error/operator=" title="cpp/error/system error/operator="> <span class="t-lines"><span>operator=</span></span></a></div> </td> <td> replaces the <code>system_error</code> object <br> <span class="t-mark">(public member function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="system_error/code" title="cpp/error/system error/code"> <span class="t-lines"><span>code</span></span></a></div> </td> <td> returns error code <br> <span class="t-mark">(public member function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="system_error/what" title="cpp/error/system error/what"> <span class="t-lines"><span>what</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> returns an explanatory string <br> <span class="t-mark">(virtual public member function)</span>  </td>
</tr> </table> <div class="t-inherited"> <h2 id="Inherited_from_std::exception"> Inherited from <a href="exception" title="cpp/error/exception"> std::exception</a> </h2> <h3 id="Member_functions_2"> Member functions</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="exception/~exception" title="cpp/error/exception/~exception"> <span class="t-lines"><span>(destructor)</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> destroys the exception object <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="exception/what" title="cpp/error/exception/what"> <span class="t-lines"><span>what</span></span></a></div>
<div><span class="t-lines"><span><span class="t-cmark">[virtual]</span></span></span></div> </td> <td> returns an explanatory string <br> <span class="t-mark">(virtual public member function of <code>std::exception</code>)</span>  </td>
</tr> </table> </div> <h3 id="Example"> Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;thread&gt;
#include &lt;iostream&gt;
#include &lt;system_error&gt;
 
int main()
{
    try {
        std::thread().detach(); // attempt to detach a non-thread
    } catch(const std::system_error&amp; e) {
        std::cout &lt;&lt; "Caught system_error with code " &lt;&lt; e.code() 
                  &lt;&lt; " meaning " &lt;&lt; e.what() &lt;&lt; '\n';
    }
}</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">Caught system_error with code generic:22 meaning Invalid argument</pre></div> </div>           <div class="_attribution">
  <p class="_attribution-p">
    &copy; cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/system_error" class="_attribution-link">https://en.cppreference.com/w/cpp/error/system_error</a>
  </p>
</div>
